site_name: OpenDRR Model Factory
site_url: https://github.com/wkhchow/model-factory

nav:
- Home: index.md
- 'OpenDRR Database/SQL Documentation': intro.md
- 'National Human Settlement Layers': nhsl.md
- 'Schemas': schemas.md
theme: readthedocs
