
DROP TABLE IF EXISTS sovi.sovi_census_canada CASCADE;

-- create table
CREATE TABLE sovi.sovi_census_canada(
PRIMARY KEY(sauidt),
sauidt varchar,
sauidi integer,
dauidt varchar,
dauidi integer,
fsauid varchar,
csdname varchar,
cdname varchar,
ername varchar,
prname varchar,
lon float,
lat float,
bldgnum float,
costasset float,
costbldg float,
popday float,
popnight float,
poptrnst float,
censuspop float,
censusbldg float,
censusdu float,
area_km2 float,
area_ha float,
shape_length float,
shape_area float,
sauid_pc varchar,
landuse varchar,
dauidt_1 varchar,
dauid_i integer,
dauid_lon float,
dauid_lat float,
adauid varchar,
ctuid varchar,
ctname varchar,
cfsauid varchar,
csduid varchar,
csdtype varchar,
saccode varchar,
sactype varchar,
cduid varchar,
cdtype varchar,
ccsuid varchar,
ccsname varchar,
cmauid varchar,
cmapuid varchar,
cmaname varchar,
cmatype varchar,
eruid varchar,
pruid varchar,
sauid_km2 float,
age_gt65 float,
age_lt6 float,
age_median float,
health_job float,
indigenous float,
no_engfr float,
nosec_school float,
vis_min float,
pub_trans float,
inc_hshld float,
inc_indv float,
inc_lowdecile float,
retail_job float,
shltr_gt30 float,
unemployed float,
work_none float,
work_parttime float,
employ_inc float,
fam_gt5 float,
imm_lt5 float,
live_alone float,
lonepar3kids float,
moved_lt1 float,
nowrkplace float,
bus_ha float,
hshld_mntn1 float,
hshld_mntnage float,
hshld_nsuit float,
pop_ha float,
pre_1975 float,
renter float,
dauid_text varchar
);

/*
-- import exposure from csv
COPY sovi.sovi_census_canada (sauidt,sauidi,dauidt,dauidi,fsauid,csdname,cdname,ername,prname,lon,lat,bldgnum,costasset,costbldg,popday,popnight,poptrnst,censuspop,censusbldg,censusdu,area_km2,area_ha,shape_length,shape_area,sauid_pc,
landuse,dauidt_1,dauid_i,dauid_lon,dauid_lat,adauid,ctuid,ctname,cfsauid,csduid,csdtype,saccode,sactype,cduid,cdtype,ccsuid,ccsname,cmauid,cmapuid,cmaname,cmatype,eruid,pruid,sauid_km2,age_gt65,age_lt6,age_median,health_job,indigenous,
no_engfr,nosec_school,vis_min,pub_trans,inc_hshld,inc_indv,inc_lowdecile,retail_job,shltr_gt30,unemployed,work_none,work_parttime,employ_inc,fam_gt5,imm_lt5,live_alone,lonepar3kids,moved_lt1,nowrkplace,bus_ha,hshld_mntn1,hshld_mntnage,
hshld_nsuit,pop_ha,pre_1975,renter,dauid_text)
    FROM '/usr/src/app/social-vulnerability-census_2021.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;\

-- create index
CREATE INDEX sovi_census_canada_idx ON sovi.sovi_census_canada (sauidt);
*/