-- script to generate Canada exposure table

DROP TABLE IF EXISTS exposure.canada_exposure CASCADE;

-- create table
CREATE TABLE exposure.canada_exposure(
    PRIMARY KEY (id),
    objectid varchar,
    id varchar,
    SauidLat float,
    SauidLon float,
    Sauid_km2 float,
    Sauid_ha float,
    LandUse varchar,
    taxonomy varchar,
    number float,
    structural float,
    nonstructural float,
    contents float,
    retrofitting float,
    day float,
    night float,
    transit float,
    GenOcc varchar,
    OccType varchar,
    OccClass1 varchar,
    OccClass2 varchar,
    PopDU float,
    GenType varchar,
    BldgType varchar,
    NumFloors float,
    Bldg_ft2 float,
    BldYear float,
    BldEpoch varchar,
    SSC_Zone varchar,
    EqDesLev varchar,
    sauid varchar,
    dauid varchar,
    adauid varchar,
    fsauid varchar,
    csduid varchar,
    csdname varchar,
    cduid varchar,
    cdname varchar,
    SAC varchar,
    eruid varchar,
    ername varchar,
    pruid varchar,
    prname varchar,
    ss_region varchar,
    nation varchar
);