-- create individual psra schema for provinces
CREATE SCHEMA IF NOT EXISTS psra_ab;
CREATE SCHEMA IF NOT EXISTS psra_bc;
CREATE SCHEMA IF NOT EXISTS psra_mb;
CREATE SCHEMA IF NOT EXISTS psra_nb;
CREATE SCHEMA IF NOT EXISTS psra_nl;
CREATE SCHEMA IF NOT EXISTS psra_ns;
CREATE SCHEMA IF NOT EXISTS psra_nt;
CREATE SCHEMA IF NOT EXISTS psra_nu;
CREATE SCHEMA IF NOT EXISTS psra_on;
CREATE SCHEMA IF NOT EXISTS psra_pe;
CREATE SCHEMA IF NOT EXISTS psra_qc;
CREATE SCHEMA IF NOT EXISTS psra_sk;
CREATE SCHEMA IF NOT EXISTS psra_yt;
CREATE SCHEMA IF NOT EXISTS psra_canada;